---
- include: epel7.yml

- copy:
    dest: /etc/yum.repos.d/walters-buildtools.repo
    content: |
      [walters-buildtools]
      name=Copr repo for buildtools owned by walters
      baseurl=https://copr-be.cloud.fedoraproject.org/results/walters/buildtools/epel-7-$basearch/
      gpgcheck=1
      gpgkey=https://copr-be.cloud.fedoraproject.org/results/walters/buildtools/pubkey.gpg
      enabled=1
      enabled_metadata=1

- copy:
    dest: /etc/yum.repos.d/atomic7-testing.repo
    content: |
      [atomic7-testing]
      name=CentOS7 Atomic Testing
      baseurl=http://cbs.centos.org/repos/atomic7-testing/x86_64/os/
      gpgcheck=0
      enabled=1

# Ensure we see fresh data
- command: yum clean expire-cache

# Add in here direct RPM links, for things that are still pending repodata
- command: yum -y localinstall {{ item }}
  with_items:
    - https://kojipkgs.fedoraproject.org//packages/python-distro/1.0.1/2.el7/noarch/python2-distro-1.0.1-2.el7.noarch.rpm

# Disable epel testing to work around https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-6fb8d59d10
- yum: name={{ item }} state=latest disablerepo=epel-testing
  with_items:
    - rsync
    - mock
    - libsolv
    - glib2
    - ostree
    - rpm-ostree
    - rpm-ostree-toolbox
    - fedpkg
    - PyYAML
    - rpmdistro-gitoverlay
    - libgsystem
    - genisoimage
    - ansible
    - virt-install

- service: name={{ item }} state=started
  with_items:
    - docker
    - libvirtd

# nspawn is better, also https://lists.fedoraproject.org/pipermail/buildsys/2015-July/004833.html
# Also https://bugzilla.redhat.com/show_bug.cgi?id=1328212
- lineinfile: dest=/etc/mock/site-defaults.cfg line={{ item }}
  with_items:
    - "config_opts['plugin_conf']['tmpfs_enable'] = True"
    - "config_opts['use_nspawn'] = True"

- user: name={{ item }} groups=mock,wheel,libvirt
  with_items:
    - builder
    - prbuilder

- lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"

- authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  with_items:
    - builder
    - prbuilder
